<?php
/**
 * Paybras
 *
 * @category   Payments
 * @package    Xpd_Paybras
 * @license    OSL v3.0
 */
 ?>
<?php
    $_code = $this->getMethodCode();
    //feito para ter compatibilidade com o OneStepCheckout
    $route = $this->getRequest()->getRequestedRouteName();
    if($route == 'onestepcheckout') {
        $fieldCode = '['.$_code.']';
    }
    else {
        $fieldCode = '';
    }
?>

<script type="text/javascript">

    <?php $quote = Mage::getSingleton('checkout/session')->getQuote(); ?>
    <?php $billingaddress = $quote->getBillingAddress(); ?>
    <?php $customer = Mage::getSingleton('customer/session')->getCustomer(); ?>
    <?php $name = $billingaddress->getFirstname() . ' ' . $billingaddress->getLastname(); ?>
    
    nomeComprador = '<?php echo $name; ?>';
    nomeTitular = '';
    
    new MaskedInput('input[name="payment[cc_cpftitular]"]', '999.999.999-99');
    new MaskedInput('input[name="payment[cc_phone]"]', '(99)99999999?9');
    maskcid = new MaskedInput('input[name="payment[cc_cid]"]', '999');
        
        Validation.add('cpftitular','CPF Inválido',function(valueCPF) {
        var cpf = valueCPF.replace(/[^\d]+/g,'');
                if(cpf == '') return true;
                while(cpf.length < 11) cpf = "0"+ cpf;
                var expReg = /^0+$|^1+$|^2+$|^3+$|^4+$|^5+$|^6+$|^7+$|^8+$|^9+$/;
                var a = [];
                var b = new Number;
                var c = 11;
                for (i=0; i<11; i++){
                        a[i] = cpf.charAt(i);
                        if (i < 9) b += (a[i] * --c);
                }
                if ((x = b % 11) < 2) {
                        a[9] = 0
                } 
                else {
                        a[9] = 11-x
                }

                b = 0;
                c = 11;

                for (y=0; y<10; y++) b += (a[y] * c--);
                if ((x = b % 11) < 2) {
                        a[10] = 0;
                }
                else {
                        a[10] = 11-x;
                }
                if ((cpf.charAt(9) != a[9]) || (cpf.charAt(10) != a[10]) || cpf.match(expReg)) return false;
                return true;
    });
    
    
    isSelected = function() {
            
        var radioObj = $$('.card-logo .radio');
    
        for(var i=0; i<radioObj.length; i++) {
            if( radioObj[i].checked ) {
                return true;
            }
        }
        
        return false;
    };
    
    Validation.add('radioss','Selecione uma Bandeira',function() { return isSelected(); });

    Validation.add('cccard','Cartão Inválido',function(ccnum) {
        ccnum = ccnum.split("-").join("");
    
        var checksum = 0;
        for (var i=(2-(ccnum.length % 2)); i<=ccnum.length; i+=2) {
            checksum += parseInt(ccnum.charAt(i-1));
        }
        
        for (var i=(ccnum.length % 2) + 1; i<ccnum.length; i+=2) {
            var digit = parseInt(ccnum.charAt(i-1)) * 2;
            if (digit < 10) { checksum += digit; } else { checksum += (digit-9); }
        }
        
        if ((checksum % 10) == 0) {
            if(isSelected()) {
                return true;
            }
        }
        else {
            $$('.card-logo input[type="radio"]:checked').each(function(c){
                $(c).checked = false;
            });
            $$('.seleciona-bandeiras-cards label').each(function(e,i){
                $(e).removeClassName('selecionada');
            });
            return false;
        }
    });

</script>
<fieldset class="form-list">
<?php $_ccType = $this->getInfoData('cc_type') ?>
<?php $parcela_count = count($this->getParcelas()); //var_dump($this->getParcelas());?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none;">

    <li id="li-cc">
    <ul id="cc">

        <li class="valida-bandeira" style="display: block">
            <div class="input-box" style="width: 100%;">
                <ul class="card-logo" >
        		<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
        			<li id="li-card-<?php echo $_typeCode ?>" class="seleciona-bandeiras-cards">
        				<label for="opt-<?php echo $_typeCode ?>"><img src="<?php echo $this->getSkinUrl('images/paybras/'.$_typeCode.'/'. $parcela_count .'x.gif') ?>" /></label>
                        
                        <input type="radio" class="radio" name="payment[cc_type]" id="opt-<?php echo $_typeCode ?>" value="<?php echo $_typeCode ?>" onclick="onCardChange(this);" style="display: none;"/>
        			</li>
        		<?php endforeach; ?>
        		</ul>
                <input type="hidden" class="radioss" />
            </div>
        </li>
		
		<?php if(Mage::getStoreConfig('payment/paybras/installments')): ?>
		<li style="margin-bottom: 20px;">
            <label for="<?php echo $_code ?>_parcelas"><?php echo $this->__('Parcelas') ?> </label><br />
            <div class="input-box">
                <select id="<?php echo $_code ?>_cc_parcelas" name="payment[cc_parcelas]" class="required-entry">
    		<?php $j=1; foreach($this->getParcelas() as $parcela): ?>
                    <?php if($j == 1): ?>
                    <option value="<?php echo $j; ?>"><?php echo 'À vista - '.$this->helper('checkout')->formatPrice($parcela); ?></option>
                    <?php else: ?>
    				<option value="<?php echo $j ?>"><?php echo $j.'x - '.$this->helper('checkout')->formatPrice($parcela).' = '. $this->helper('checkout')->formatPrice($parcela*$j); ?></option>
                    <?php endif; ?>
    		<?php $j+=1; endforeach; ?>
                </select>
            </div>
        </li>
		<?php endif; ?>
		
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label><br />
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" onblur="comparaNome(this.value,'<?php echo Mage::getBaseUrl(); ?>');"/>
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label><br />
            <div class="input-box">
                <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" onkeydown="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros);verifyType(this);" class="input-text required-entry cccard" value="" maxlength="16" />
            </div>
        </li>
        <li id="<?php echo $_code ?>_cc_type_exp_div">
            <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label><br />
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v[0] == 'M' ? $v : substr($v,0,3); ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                    <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                    <?php foreach ($this->getCcYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>
        <?php echo $this->getChildHtml() ?>
        <?php if($this->hasVerification()): ?>
        <li>
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label><br />
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" size="5" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" maxlength="4" />
                </div>
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
            </div>
        </li>
        <?php endif; ?>
                
        <li id="<?php echo $_code ?>_cc_cpftitular_div" style="display: none;">
            <label for="<?php echo $_code ?>_cc_cpftitular" class="required"><em>*</em><?php echo $this->__("TAX/VAT of Card's Owner") ?></label><br />
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cpftitular required-entry" id="<?php echo $_code ?>_cc_cpftitular" name="payment[cc_cpftitular]" value="" maxlength="14" />
                </div>
            </div>
        </li>
        
        <li id="<?php echo $_code ?>_cc_phone_div" style="display: none;">
            <label for="<?php echo $_code ?>_cc_phone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label><br />
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" title="<?php echo $this->__('Telephone') ?>" class="input-text telephone required-entry" id="<?php echo $_code ?>_cc_phone" name="payment[cc_phone]" value="" maxlength="14" />
                </div>
            </div>
        </li>
        
        <li id="<?php echo $_code ?>_cc_type_dob_div" style="display: none;">
            <label for="<?php echo $_code ?>_dob" class="required"><em>*</em><?php echo $this->__('Date of Birthday') ?></label><br />
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_dob" name="payment[cc_dob_day]" class="day validate-not-negative-number  required-entry">
                    <?php for($i=0;$i<=31;$i++): ?>
                        <option value="<?php echo $i?$i:'' ?>"<?php if($i == 0): ?> selected="selected"<?php endif ?>><?php echo $i == 0 ? 'Dia' : $i; ?></option>    
                    <?php endfor; ?>
                    </select>
                </div>
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_dob_mo" name="payment[cc_dob_month]" class="month validate-not-negative-number required-entry">
                    <?php $_ccExpMonth = $this->getInfoData('cc_exp_month'); ?>
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v[0] == 'M' ? $v : substr($v,0,3); ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_dob_yr" name="payment[cc_dob_year]" class="year validate-not-negative-number required-entry">
                    <?php for($i=((int)date('Y') - 9);$i>((int)date('Y') - 100);$i--): ?>
                        
                        <option value="<?php echo $i ? $i == ((int)date('Y') - 9) ? 'Ano' : $i : '' ?>"<?php if($i == ((int)date('Y') - 9)): ?> selected="selected"<?php endif ?>><?php echo $i == ((int)date('Y') - 9) ? 'Ano' : $i; ?></option>    
                    <?php endfor; ?>
                    </select>
                </div>
            </div>
        </li>
    </ul>
    </li>
        
    <input title="<?php echo $this->__('Escolha da Forma de Pagamento') ?>" name="payment[check_formapagamento]" type="hidden" id="<?php echo $_code ?>_check_formapagamento" value="cartao" />
</ul>
</fieldset>
