<?php
/**
 * Paybras
 *
 * @category   Payments
 * @package    Xpd_Paybras
 * @license    OSL v3.0
 */
 ?>
 <?php
    $_code = $this->getMethodCode();
    //feito para ter compatibilidade com o OneStepCheckout
    $route = $this->getRequest()->getRequestedRouteName();
    if($route == 'onestepcheckout') {
        $fieldCode = '['.$_code.']';
    }
    else {
        $fieldCode = '';
    }
?>
<fieldset class="form-list">
<ul id="payment_form_<?php echo $_code; ?>" style="display:none;">
	<li>
		<p><?php echo Mage::getStoreConfig('payment/paybrastef/texttef'); ?></p>
		<p>Escolha seu banco:</p>
		<?php $tefTypes = explode(",",Mage::getStoreConfig('payment/paybrastef/teftypes')); ?>
		<select id="<?php echo $_code ?>_tef_banco" name="payment[tef_banco]" class="tef_banco required-entry">
			<?php foreach($tefTypes as $debito): ?>
				<?php if($debito == 'tef_bb'): ?>
					<option value="tef_bb">Banco do Brasil</option>
				<?php endif; ?>
				<?php if($debito == 'tef_bradesco'): ?>
					<option value="tef_bradesco">Bradesco</option>
				<?php endif; ?>
				<?php if($debito == 'tef_itau'): ?>
					<option value="tef_itau">Itaú</option>
				<?php endif; ?>
			<?php endforeach; ?>
		</select>
	</li>
</ul>
</fieldset>